# coding: utf-8
#
#
# user-graph need to be generated by the following script
# tools/generate-u-u-matrix.py
import os
from collections import deque, defaultdict
import numpy as np
import scipy.sparse as sp
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.utils import remove_self_loops, degree
from utils.utils import build_non_zero_graph, build_knn_normalized_graph

from common.abstract_recommender import GeneralRecommender


class TAMER(GeneralRecommender):
    def __init__(self, config, dataset):
        super(TAMER, self).__init__(config, dataset)

        num_user = self.n_users
        num_item = self.n_items
        batch_size = config['train_batch_size']  # not used
        dim_x = config['embedding_size']
        self.feat_embed_dim = config['feat_embed_dim']
        self.n_layers = config['n_mm_layers']
        self.knn_k = config['knn_k']
        self.alpha_interest = config['alpha_interest']
        self.alpha_text_p = config['alpha_text_p']
        self.alpha_text_z = config['alpha_text_z']
        self.alpha_image_p = config['alpha_image_p']
        self.alpha_image_z = config['alpha_image_z']
        self.alpha_video_p = config['alpha_video_p']
        self.alpha_video_z = config['alpha_video_z']
        has_id = True
        self.config = config
        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.k = 40
        self.aggr_mode = config['aggr_mode']
        self.user_aggr_mode = 'softmax'
        self.num_layer = 1
        self.cold_start = 0
        self.dataset = dataset
        # self.construction = 'weighted_max'
        self.construction = 'cat'
        self.reg_weight = config['reg_weight']
        self.drop_rate = 0.1
        self.v_rep = None
        self.t_rep = None
        self.v_preference = None
        self.t_preference = None
        self.dim_latent = 64
        self.dim_feat = 128
        self.embedding_size = self.dim_latent * 3
        self.MLP_v = nn.Linear(self.dim_latent, self.dim_latent, bias=False)
        self.MLP_t = nn.Linear(self.dim_latent, self.dim_latent, bias=False)
        self.num_of_session_k = config['num_of_session_k']
        self.gamma = config['gamma']
        self.theta = 1.0
        self.tau = config['tau']
        self.degree_n = config['degree_n']

        self.mm_adj = None
        # load data
        dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        self.data_path = dataset_path

        self.item_graph_dict = np.load(os.path.join(dataset_path, config['item_graph_dict_file']),
                                       allow_pickle=True).item()
        weighted_binary_relations, co_adj = self.get_co_occurrence_item()
        self.co_adj = co_adj
        self.weighted_binary_relations = weighted_binary_relations

        # load inters
        self.train_interactions = dataset.inter_matrix(form='coo').astype(np.float32)
        edge_index = self.pack_edge_index(self.train_interactions)
        self.edge_index = torch.tensor(edge_index, dtype=torch.long).t().contiguous().to(self.device)
        self.edge_index = torch.cat((self.edge_index, self.edge_index[[1, 0]]), dim=1)

        if self.ip_feat is not None:
            self.ip_embedding = nn.Embedding.from_pretrained(self.ip_feat, freeze=False)
            _, self.ip_adj = self.get_knn_adj_mat(self.ip_embedding.weight.detach())
        if self.iz_feat is not None:
            self.iz_embedding = nn.Embedding.from_pretrained(self.iz_feat, freeze=False)
            _, self.iz_adj = self.get_knn_adj_mat(self.iz_embedding.weight.detach())
        if self.tp_feat is not None:
            self.tp_embedding = nn.Embedding.from_pretrained(self.tp_feat, freeze=False)
            _, self.tp_adj = self.get_knn_adj_mat(self.tp_embedding.weight.detach())
        if self.tz_feat is not None:
            self.tz_embedding = nn.Embedding.from_pretrained(self.tz_feat, freeze=False)
            _, self.tz_adj = self.get_knn_adj_mat(self.tz_embedding.weight.detach())
        if self.vp_feat is not None:
            self.vp_embedding = nn.Embedding.from_pretrained(self.vp_feat, freeze=False)
            _, self.vp_adj = self.get_knn_adj_mat(self.vp_embedding.weight.detach())
        if self.vz_feat is not None:
            self.vz_embedding = nn.Embedding.from_pretrained(self.vz_feat, freeze=False)
            _, self.vz_adj = self.get_knn_adj_mat(self.vz_embedding.weight.detach())

        self.ip_adj = self.build_enhanced_adj(self.ip_embedding, self.ip_adj)
        self.iz_adj = self.build_enhanced_adj(self.iz_embedding, self.iz_adj)
        self.tp_adj = self.build_enhanced_adj(self.tp_embedding, self.tp_adj)
        self.tz_adj = self.build_enhanced_adj(self.tz_embedding, self.tz_adj)
        self.vp_adj = self.build_enhanced_adj(self.vp_embedding, self.vp_adj)
        self.vz_adj = self.build_enhanced_adj(self.vz_embedding, self.vz_adj)
        torch.cuda.empty_cache()

        self.edge_index = torch.cat((self.edge_index, self.get_CF_edge()), dim=1)  # CF edge

        if self.ip_feat is not None and self.tp_feat is not None:
            self.mm_adj = self.alpha_text_p * self.tp_adj + self.alpha_text_z * self.tz_adj + \
                          self.alpha_image_p * self.ip_adj + self.alpha_image_z * self.iz_adj + \
                          self.alpha_video_p * self.vp_adj + self.alpha_video_z * self.vz_adj + \
                          self.alpha_interest * self.co_adj

        # weight
        self.weight_u = nn.Parameter(nn.init.xavier_normal_(
            torch.tensor(np.random.randn(self.num_user, 6, 1), dtype=torch.float32, requires_grad=True)))
        self.weight_u.data = F.softmax(self.weight_u, dim=1)

        if self.ip_feat is not None:
            self.ip_gcn = GCN(config, self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                              num_layer=self.num_layer, has_id=has_id, dropout=self.drop_rate, dim_latent=64,
                              device=self.device, features=self.ip_feat)
        if self.iz_feat is not None:
            self.iz_gcn = GCN(config, self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                              num_layer=self.num_layer, has_id=has_id, dropout=self.drop_rate, dim_latent=64,
                              device=self.device, features=self.iz_feat)
        if self.tp_feat is not None:
            self.tp_gcn = GCN(config, self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                              num_layer=self.num_layer, has_id=has_id, dropout=self.drop_rate, dim_latent=64,
                              device=self.device, features=self.tp_feat)

        if self.tz_feat is not None:
            self.tz_gcn = GCN(config, self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                              num_layer=self.num_layer, has_id=has_id, dropout=self.drop_rate, dim_latent=64,
                              device=self.device, features=self.tz_feat)
        if self.vp_feat is not None:
            self.vp_gcn = GCN(config, self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                              num_layer=self.num_layer, has_id=has_id, dropout=self.drop_rate, dim_latent=64,
                              device=self.device, features=self.vp_feat)

        if self.vz_feat is not None:
            self.vz_gcn = GCN(config, self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                              num_layer=self.num_layer, has_id=has_id, dropout=self.drop_rate, dim_latent=64,
                              device=self.device, features=self.vz_feat)

    def build_enhanced_adj(self, embedding, ori_adj):
        ori_adj = ori_adj.to('cpu')
        sim = self.build_sim(embedding.weight.detach()).to('cpu')
        session_enhanced = self.build_session_tree(sim)
        session_enhanced_adj = self.build_non_zero_graph(session_enhanced, is_sparse=False,
                                                         norm_type='sym')
        adj = (torch.add(ori_adj / 2, session_enhanced_adj)).to(self.device)
        return adj

    def build_session_tree(self, sim_matrix):
        session_enhanced_z = torch.zeros_like(sim_matrix).to('cpu')
        for i in range(self.num_item):
            n_order_relationships = self.find_weighted_n_order_relationships(self.weighted_binary_relations, idx=i,
                                                                             n=self.degree_n)
            _, cols3 = torch.topk(sim_matrix[i], self.knn_k)
            session_enhanced_z[i, cols3] += sim_matrix[i, cols3] / 2
            for order, relation in n_order_relationships.items():
                # current order clos
                enhanced_clos = []
                values = []
                for tail, value in relation:
                    enhanced_clos.append(tail)
                    values.append(value ** self.tau)
                order_coefficient = self.gamma * np.exp(-1 * (order - 1))
                coefficient = torch.tensor([order_coefficient * x for x in values],
                                           dtype=torch.float32).to(sim_matrix.device)
                session_enhanced_z[i, enhanced_clos] += coefficient * sim_matrix[i, enhanced_clos]
        return session_enhanced_z

    def get_co_occurrence_item(self):
        graph_co = self.item_graph_dict
        indices = []
        result = []
        weighted_binary_relations = {}
        for indx, v in graph_co.items():
            length = 0
            if len(v[0]) >= self.num_of_session_k:
                length = self.num_of_session_k
            else:
                length = len(v[0])
            indices.append(np.full(length, indx))
            result.append(v[0][:self.num_of_session_k])

            session_dict = {}
            for i in range(length):
                session_dict[v[0][i]] = v[1][i]
            weighted_binary_relations[indx] = session_dict

        indices = torch.IntTensor(np.concatenate(indices)).to(self.device)
        result = torch.IntTensor(np.concatenate(result)).to(self.device)

        indices = torch.stack((torch.flatten(indices), torch.flatten(result)), 0).to(torch.int64).to(self.device)
        adj_size = torch.Size([len(graph_co), len(graph_co)])
        return weighted_binary_relations, self.compute_normalized_laplacian(indices, adj_size)

    def find_weighted_n_order_relationships(self, graph, idx, n):
        order_dict = defaultdict(list)
        visited = set()
        visited.add(idx)
        current_level_nodes = [(idx, 0)]
        for order in range(1, n + 1):
            next_level_nodes = []
            for node, _ in current_level_nodes:
                for neighbor, weight in graph.get(node, {}).items():
                    if neighbor not in visited:
                        visited.add(neighbor)
                        next_level_nodes.append((neighbor, weight))
            if next_level_nodes:
                if order > 1:
                    '''
                    next_level_nodes = sorted(next_level_nodes, key=lambda x: x[1], reverse=True)[
                                       :int(len(next_level_nodes) / ((order - 1) * 2))
                                       ]
                    '''
                    next_level_nodes = sorted(next_level_nodes, key=lambda x: x[1], reverse=True)[
                                       :int(len(current_level_nodes) / ((order - 1) * 2))
                                       ]
                    # '''

                order_dict[order] = next_level_nodes
            current_level_nodes = next_level_nodes

        return dict(order_dict)

    def build_non_zero_graph(self, adj, is_sparse=True, norm_type='sym'):
        device = adj.device
        nonzero_indices = adj.nonzero()
        i = nonzero_indices.T
        v = adj[nonzero_indices[:, 0], nonzero_indices[:, 1]]
        edge_index, edge_weight = self.get_sparse_laplacian(i, v, normalization=norm_type, num_nodes=adj.shape[0])
        return torch.sparse_coo_tensor(edge_index, edge_weight, adj.shape)

    def build_knn_normalized_graph(self, adj, topk, is_sparse, norm_type):
        device = adj.device
        knn_val, knn_ind = torch.topk(adj, topk, dim=-1)
        if is_sparse:
            tuple_list = [[row, int(col)] for row in range(len(knn_ind)) for col in knn_ind[row]]
            row = [i[0] for i in tuple_list]
            col = [i[1] for i in tuple_list]
            i = torch.LongTensor([row, col]).to(device)
            v = knn_val.flatten()
            edge_index, edge_weight = self.get_sparse_laplacian(i, v, normalization=norm_type, num_nodes=adj.shape[0])
            return torch.sparse_coo_tensor(edge_index, edge_weight, adj.shape)
        else:
            weighted_adjacency_matrix = (torch.zeros_like(adj)).scatter_(-1, knn_ind, knn_val)
            return self.get_dense_laplacian(weighted_adjacency_matrix, normalization=norm_type)

    def get_knn_adj_mat(self, mm_embeddings):
        context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
        sim = torch.mm(context_norm, context_norm.transpose(1, 0))
        _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
        adj_size = sim.size()
        del sim
        # construct sparse adj
        indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
        indices0 = torch.unsqueeze(indices0, 1)
        indices0 = indices0.expand(-1, self.knn_k)
        indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
        # norm
        return indices, self.compute_normalized_laplacian(indices, adj_size)

    def compute_normalized_laplacian(self, indices, adj_size):
        adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
        row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
        r_inv_sqrt = torch.pow(row_sum, -0.5)
        rows_inv_sqrt = r_inv_sqrt[indices[0]]
        cols_inv_sqrt = r_inv_sqrt[indices[1]]
        values = rows_inv_sqrt * cols_inv_sqrt
        return torch.sparse.FloatTensor(indices, values, adj_size)

    def build_normalized_laplacian(self, vertex_count, hyperedges):
        num_edges = len(hyperedges)
        A = np.zeros((vertex_count, num_edges))
        for j, edge in enumerate(hyperedges):
            for v in edge:
                A[v, j] = 1
        vertex_degrees = np.sum(A, axis=1)
        D_v = np.diag(vertex_degrees)
        edge_degrees = np.sum(A, axis=0)
        D_e = np.diag(edge_degrees)
        if np.any(vertex_degrees == 0):
            raise ValueError("error")
        if np.any(edge_degrees == 0):
            raise ValueError("error")
        D_v_inv_sqrt = np.diag(1 / np.sqrt(vertex_degrees))
        D_e_inv = np.linalg.inv(D_e)
        I = np.eye(vertex_count)
        L = I - D_v_inv_sqrt @ A @ D_e_inv @ A.T @ D_v_inv_sqrt
        return L

    def get_sparse_laplacian(self, edge_index, edge_weight, num_nodes, normalization='none'):
        from torch_scatter import scatter_add
        row, col = edge_index[0], edge_index[1]
        deg = scatter_add(edge_weight, row, dim=0, dim_size=num_nodes)
        deg[deg <= 0] = 1e-7
        if normalization == 'sym':
            deg_inv_sqrt = deg.pow_(-0.5)
            deg_inv_sqrt.masked_fill_(deg_inv_sqrt == float('inf'), 0.)
            edge_weight = deg_inv_sqrt[row] * edge_weight * deg_inv_sqrt[col]
            edge_weight.masked_fill_(edge_weight <= 1e-7, 1e-7)
        elif normalization == 'rw':
            deg_inv = 1.0 / deg
            deg_inv.masked_fill_(deg_inv == float('inf'), 0)
            edge_weight = deg_inv[row] * edge_weight
        return edge_index, edge_weight

    def get_dense_laplacian(self, adj, normalization='none'):
        if normalization == 'sym':
            rowsum = torch.sum(adj, -1)
            d_inv_sqrt = torch.pow(rowsum, -0.5)
            d_inv_sqrt[torch.isinf(d_inv_sqrt)] = 0.
            d_mat_inv_sqrt = torch.diagflat(d_inv_sqrt)
            L_norm = torch.mm(torch.mm(d_mat_inv_sqrt, adj), d_mat_inv_sqrt)
        elif normalization == 'rw':
            rowsum = torch.sum(adj, -1)
            d_inv = torch.pow(rowsum, -1)
            d_inv[torch.isinf(d_inv)] = 0.
            d_mat_inv = torch.diagflat(d_inv)
            L_norm = torch.mm(d_mat_inv, adj)
        elif normalization == 'none':
            L_norm = adj
        return L_norm

    def build_normalized_laplacian_with_zero_handling(self, vertex_count, hyperedges, epsilon=1e-6):
        num_edges = len(hyperedges)
        A = np.zeros((vertex_count, num_edges))
        for j, edge in enumerate(hyperedges):
            for v in edge:
                A[v, j] = 1
        vertex_degrees = np.sum(A, axis=1)
        edge_degrees = np.sum(A, axis=0)
        vertex_degrees[vertex_degrees == 0] = epsilon
        edge_degrees[edge_degrees == 0] = epsilon
        D_v = np.diag(vertex_degrees)
        D_e = np.diag(edge_degrees)
        D_v_inv_sqrt = np.diag(1 / np.sqrt(vertex_degrees))
        D_e_inv = np.linalg.inv(D_e)
        I = np.eye(vertex_count)
        L = I - D_v_inv_sqrt @ A @ D_e_inv @ A.T @ D_v_inv_sqrt
        return L

    def pre_epoch_processing(self):
        pass

    def pack_edge_index(self, inter_mat):
        rows = inter_mat.row
        cols = inter_mat.col + self.n_users
        return np.column_stack((rows, cols))

    def forward(self, interaction):
        user_nodes, pos_item_nodes, neg_item_nodes = interaction[0], interaction[1], interaction[2]
        pos_item_nodes += self.n_users
        neg_item_nodes += self.n_users

        ip_rep, self.ip_preference = self.ip_gcn(self.edge_index, self.ip_feat)
        iz_rep, self.iz_preference = self.iz_gcn(self.edge_index, self.iz_feat)
        tp_rep, self.tp_preference = self.tp_gcn(self.edge_index, self.tp_feat)
        tz_rep, self.tz_preference = self.tz_gcn(self.edge_index, self.tz_feat)
        vp_rep, self.vp_preference = self.vp_gcn(self.edge_index, self.vp_feat)
        vz_rep, self.vz_preference = self.vz_gcn(self.edge_index, self.vz_feat)

        representation = torch.cat((ip_rep, iz_rep, tp_rep, tz_rep, vp_rep, vz_rep), dim=1)

        self.ip_rep = torch.unsqueeze(ip_rep, 2)
        self.iz_rep = torch.unsqueeze(iz_rep, 2)
        self.tp_rep = torch.unsqueeze(tp_rep, 2)
        self.tz_rep = torch.unsqueeze(tz_rep, 2)
        self.vp_rep = torch.unsqueeze(vp_rep, 2)
        self.vz_rep = torch.unsqueeze(vz_rep, 2)
        user_rep = torch.cat((self.ip_rep[:self.num_user], self.iz_rep[:self.num_user], self.tp_rep[:self.num_user],
                              self.tz_rep[:self.num_user], self.vp_rep[:self.num_user], self.vz_rep[:self.num_user]),
                             dim=2)
        user_rep = self.weight_u.transpose(1, 2) * user_rep
        user_rep = torch.cat((user_rep[:, :, 0], user_rep[:, :, 1], user_rep[:, :, 2], user_rep[:, :, 3],
                              user_rep[:, :, 4], user_rep[:, :, 5]), dim=1)
        self.user_rep = user_rep
        item_rep = representation[self.num_user:]

        h = item_rep
        for i in range(self.n_layers):
            h = torch.sparse.mm(self.mm_adj, h)

        user_rep = user_rep
        item_rep = item_rep + h
        all_embedding = torch.cat((user_rep, item_rep), dim=0)

        self.result_embed = all_embedding
        user_tensor = self.result_embed[user_nodes]
        pos_item_tensor = self.result_embed[pos_item_nodes]
        neg_item_tensor = self.result_embed[neg_item_nodes]
        pos_scores = torch.sum(user_tensor * pos_item_tensor, dim=1)
        neg_scores = torch.sum(user_tensor * neg_item_tensor, dim=1)
        return pos_scores, neg_scores

    def calculate_loss(self, interaction):
        user = interaction[0]
        pos_scores, neg_scores = self.forward(interaction)
        loss_value = -torch.mean(torch.log2(torch.sigmoid(pos_scores - neg_scores)))
        reg_embedding_loss_ip = (self.ip_preference[user] ** 2).mean() if self.ip_preference is not None else 0.0
        reg_embedding_loss_iz = (self.iz_preference[user] ** 2).mean() if self.iz_preference is not None else 0.0
        reg_embedding_loss_tp = (self.tp_preference[user] ** 2).mean() if self.tp_preference is not None else 0.0
        reg_embedding_loss_tz = (self.tz_preference[user] ** 2).mean() if self.tz_preference is not None else 0.0
        reg_embedding_loss_vp = (self.vp_preference[user] ** 2).mean() if self.vp_preference is not None else 0.0
        reg_embedding_loss_vz = (self.vz_preference[user] ** 2).mean() if self.vz_preference is not None else 0.0

        reg_loss = self.reg_weight * (
                    reg_embedding_loss_ip + reg_embedding_loss_iz + reg_embedding_loss_tp + reg_embedding_loss_tz + reg_embedding_loss_vp + reg_embedding_loss_vz)
        reg_loss += self.reg_weight * (self.weight_u ** 2).mean()
        return loss_value + reg_loss

    def full_sort_predict(self, interaction):
        user_tensor = self.result_embed[:self.n_users]
        item_tensor = self.result_embed[self.n_users:]

        temp_user_tensor = user_tensor[interaction[0], :]
        score_matrix = torch.matmul(temp_user_tensor, item_tensor.t())
        return score_matrix

    def topk_sample(self, k):
        user_graph_index = []
        count_num = 0
        user_weight_matrix = torch.zeros(len(self.user_graph_dict), k)
        tasike = []
        for i in range(k):
            tasike.append(0)
        for i in range(len(self.user_graph_dict)):
            if len(self.user_graph_dict[i][0]) < k:
                count_num += 1
                if len(self.user_graph_dict[i][0]) == 0:
                    # pdb.set_trace()
                    user_graph_index.append(tasike)
                    continue
                user_graph_sample = self.user_graph_dict[i][0][:k]
                user_graph_weight = self.user_graph_dict[i][1][:k]
                while len(user_graph_sample) < k:
                    rand_index = np.random.randint(0, len(user_graph_sample))
                    user_graph_sample.append(user_graph_sample[rand_index])
                    user_graph_weight.append(user_graph_weight[rand_index])
                user_graph_index.append(user_graph_sample)

                if self.user_aggr_mode == 'softmax':
                    user_weight_matrix[i] = F.softmax(torch.tensor(user_graph_weight), dim=0)  # softmax
                if self.user_aggr_mode == 'mean':
                    user_weight_matrix[i] = torch.ones(k) / k  # mean
                continue
            user_graph_sample = self.user_graph_dict[i][0][:k]
            user_graph_weight = self.user_graph_dict[i][1][:k]

            if self.user_aggr_mode == 'softmax':
                user_weight_matrix[i] = F.softmax(torch.tensor(user_graph_weight), dim=0)  # softmax
            if self.user_aggr_mode == 'mean':
                user_weight_matrix[i] = torch.ones(k) / k  # mean
            user_graph_index.append(user_graph_sample)

        # pdb.set_trace()
        return user_graph_index, user_weight_matrix

    def get_CF_edge(self):
        edge_head = []
        edge_rear = []
        for key, value in self.item_graph_dict.items():
            neighbors = value[0][:10]
            for neighbor in neighbors:
                edge_head.append(key + self.n_users)
                edge_rear.append(neighbor + self.n_users)
                edge_head.append(neighbor + self.n_users)
                edge_rear.append(key + self.n_users)
        result = np.vstack([edge_head, edge_rear]).transpose()
        edge = torch.LongTensor(result).t().contiguous().to(self.device)
        return edge

    def get_adj_mat(self):
        adj_mat = sp.dok_matrix((self.n_users + self.n_items, self.n_users + self.n_items), dtype=np.float32)
        adj_mat = adj_mat.tolil()
        R = self.train_interactions.tolil()

        adj_mat[:self.n_users, self.n_users:] = R
        adj_mat[self.n_users:, :self.n_users] = R.T
        adj_mat = adj_mat.todok()

        def normalized_adj_single(adj):
            rowsum = np.array(adj.sum(1))

            d_inv = np.power(rowsum, -0.5).flatten()
            d_inv[np.isinf(d_inv)] = 0.
            d_mat_inv = sp.diags(d_inv)

            norm_adj = d_mat_inv.dot(adj_mat)
            norm_adj = norm_adj.dot(d_mat_inv)
            # norm_adj = adj.dot(d_mat_inv)
            # print('generate single-normalized adjacency matrix.')
            return norm_adj.tocoo()

        # norm_adj_mat = normalized_adj_single(adj_mat + sp.eye(adj_mat.shape[0]))
        norm_adj_mat = normalized_adj_single(adj_mat)
        norm_adj_mat = norm_adj_mat.tolil()
        self.R = norm_adj_mat[:self.n_users, self.n_users:]
        # norm_adj_mat = normalized_adj_single(adj_mat + sp.eye(adj_mat.shape[0]))
        return norm_adj_mat.tocsr()

    def sparse_mx_to_torch_sparse_tensor(self, sparse_mx):
        """Convert a scipy sparse matrix to a torch sparse tensor."""
        sparse_mx = sparse_mx.tocoo().astype(np.float32)
        indices = torch.from_numpy(np.vstack((sparse_mx.row, sparse_mx.col)).astype(np.int64))
        values = torch.from_numpy(sparse_mx.data)
        shape = torch.Size(sparse_mx.shape)
        return torch.sparse.FloatTensor(indices, values, shape)

    def user_graph_constract(self, features, user_graph, user_matrix):
        index = user_graph
        u_features = features[index]
        user_matrix = user_matrix.unsqueeze(1)
        u_pre = torch.matmul(user_matrix, u_features)
        u_pre = u_pre.squeeze()
        return u_pre

    def build_sim(self, mm_embeddings):
        context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
        sim = torch.mm(context_norm, context_norm.transpose(1, 0))
        return sim


class Item_Graph_sample(torch.nn.Module):
    def __init__(self, num_item, aggr_mode, dim_latent):
        super(Item_Graph_sample, self).__init__()
        self.num_item = num_item
        self.dim_latent = dim_latent
        self.aggr_mode = aggr_mode

    def forward(self, features, item_graph, item_matrix):
        index = item_graph
        u_features = features[index]
        user_matrix = item_matrix.unsqueeze(1)
        u_pre = torch.matmul(user_matrix, u_features)
        u_pre = u_pre.squeeze()
        return u_pre


class GCN(torch.nn.Module):
    def __init__(self, config, datasets, batch_size, num_user, num_item, dim_id, aggr_mode, num_layer, has_id, dropout,
                 dim_latent=None, device=None, features=None):
        super(GCN, self).__init__()
        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.datasets = datasets
        self.dim_id = dim_id
        self.dim_feat = features.size(1)
        self.dim_latent = dim_latent
        self.aggr_mode = aggr_mode
        self.num_layer = num_layer
        self.has_id = has_id
        self.dropout = dropout
        self.device = device
        self.config = config
        self.fW = nn.Parameter(torch.Tensor(3))

        self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
            np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
            gain=1).to(self.device))
        self.MLP = nn.Linear(self.dim_feat, 4 * self.dim_latent)
        self.MLP_1 = nn.Linear(4 * self.dim_latent, self.dim_latent)
        self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)
        self.ID_embedding = nn.Embedding(self.num_item, 64)
        nn.init.xavier_uniform_(self.ID_embedding.weight)

    def forward(self, edge_index, features, item_edge=None):
        temp_features = self.MLP_1(F.leaky_relu(self.MLP(features))) if self.dim_latent else features
        temp_features = torch.multiply(self.ID_embedding.weight, temp_features)

        x = torch.cat((self.preference, temp_features), dim=0).to(self.device)
        x = F.normalize(x).to(self.device)

        h = self.conv_embed_1(x, edge_index)  # equation 1
        h_1 = self.conv_embed_1(h, edge_index)
        x_hat = h + x + h_1
        return x_hat, self.preference


class Base_gcn(MessagePassing):
    def __init__(self, in_channels, out_channels, normalize=True, bias=True, aggr='add', **kwargs):
        super(Base_gcn, self).__init__(aggr=aggr, **kwargs)
        self.aggr = aggr
        self.in_channels = in_channels
        self.out_channels = out_channels

    def forward(self, x, edge_index, size=None):
        # pdb.set_trace()
        if size is None:
            edge_index, _ = remove_self_loops(edge_index)
            # edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
        x = x.unsqueeze(-1) if x.dim() == 1 else x
        # pdb.set_trace()
        return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x)

    def message(self, x_j, edge_index, size):
        if self.aggr == 'add':
            # pdb.set_trace()
            row, col = edge_index
            deg = degree(row, size[0], dtype=x_j.dtype)
            deg_inv_sqrt = deg.pow(-0.5)
            norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
            return norm.view(-1, 1) * x_j
        return x_j

    def update(self, aggr_out):
        return aggr_out

    def __repr(self):
        return '{}({},{})'.format(self.__class__.__name__, self.in_channels, self.out_channels)
